server:
  port: 8080

services:
  estimating: http://localhost:8081
  knowledgebase: http://localhost:8082
  breakdown: http://localhost:8083

spring:
  cloud:
    gateway:
      routes:
        - id: estimating
          uri: ${services.estimating}
          predicates:
            - Path=/estimate
        - id: knowledgebase
          uri: ${services.knowledgebase}
          predicates:
            - Path=/knowledgebase
        - id: breakdown
          uri: ${services.breakdown}
          predicates:
            - Path=/breakdownstructure
